<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Devo6.WorkFlow.Abstractions\Devo6.WorkFlow.Abstractions.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Devo6.WorkFlow.Engine\Devo6.WorkFlow.Engine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>engine</ToolCommandName>
    <PackageId>Devo6.WorkFlow.Cli</PackageId>
    <Version>0.1.0</Version>
    <Authors>Devo6</Authors>
    <Description>Devo6 WorkFlow command-line tool for running and validating csx workflows.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/ssaattww/Devo6.WorkFlow</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ssaattww/Devo6.WorkFlow</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
